# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: 'Release Builder Action'
description: 'Drive semantic versioned releases from the changelog file.'
inputs:
  gh-token:
    description: 'The GITHUB_TOKEN value to use of not a dry run.'
    required: false
    default: ''
  changelog:
    description: 'The changelog file to examine.'
    required: false
    default: 'CHANGELOG.md'
  tag-prefix:
    description: 'Any prefix for the tag used.'
    required: false
    default: 'v'
  artifact-dir:
    description: 'The directory to use for the artifacts generated and signed.'
    required: false
    default: 'artifacts'
  shasum-file:
    description: 'The filename to use for the shasum file.'
    required: false
    default: 'sha256sum.txt'
  meson-project:
    description: 'If set to true a meson wrap file is included in the release. (true or false)'
    required: false
    default: 'false'
  meson-provides:
    description: 'If defined sets the output meson dependency name (if a meson project).'
    required: false
    default: ''
  dry-run:
    description: 'If the action should just perform a dry run. (true or false)'
    required: false
    default: 'false'
outputs:
  release-name:
    description: 'Release Name'
    value: ${{ steps.make-release.outputs.release-name }}
  release-body:
    description: 'Release Body'
    value: ${{ steps.make-release.outputs.release-body }}
  artifact-dir:
    description: 'Artifact Directory'
    value: ${{ steps.make-release.outputs.artifact-dir }}
runs:
  using: "composite"
  steps:
    - id: make-release
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go run . \
          --gh-repository  ${{ github.repository }}  \
          --gh-workspace   ${{ github.workspace }}   \
          --gh-token       ${{ inputs.gh-token }}       \
          --changelog      ${{ inputs.changelog }}      \
          --tag-prefix     ${{ inputs.tag-prefix }}     \
          --artifact-dir   ${{ inputs.artifact-dir }}   \
          --shasum-file    ${{ inputs.shasum-file }}    \
          --meson-project  ${{ inputs.meson-project }}  \
          --meson-provides ${{ inputs.meson-provides }} \
          --dry-run        ${{ inputs.dry-run }}
